// ARCHIVO GENERADO — no editar a mano.
// Se regenera con `pnpm ui:barrel` o automáticamente tras `pnpm ui:add <componente>`.

export * from './accordion'
export * from './alert'
export * from './avatar'
export * from './badge'
export * from './breadcrumb'
export * from './button'
export * from './card'
export * from './checkbox'
export * from './command'
export * from './dialog'
export * from './dropdown-menu'
export * from './input'
export * from './input-group'
export * from './label'
export * from './pagination'
export * from './popover'
export * from './progress'
export * from './radio-group'
export * from './select'
export * from './separator'
export * from './sheet'
export * from './sidebar'
export * from './skeleton'
export * from './switch'
export * from './table'
export * from './tabs'
export * from './textarea'
export * from './tooltip'
